fix fastify deprecation warning
immobiliare/fastify-sentry pull request #630
Opened 2023-09-14 09:06 UTC by tomasstrejcek

fixing (node:20436) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.

tbh I was expecting it to be bigger :)

side note: from my understanding of process-warning used in fastify, each deprecation warning should be surfaced only once, any idea why do I see it again and again (in our test suites at least, wasn't brave enough to send it to production like this)

2023-09-14 13:10 UTC, tomasstrejcek commented
@dnlup can we get this out soon please? :)

2023-09-15 07:08 UTC, dnlup commented
> fixing #628 (node:20436) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
> 
> tbh I was expecting it to be bigger :)
> 
> side note: from my understanding of process-warning used in fastify, each deprecation warning should be surfaced only once, any idea why do I see it again and again (in our test suites at least, wasn't brave enough to send it to production like this)

Thank you @tomasstrejcek ! In the tests in this plugin it should be expected to see the warning multiple times because each test file runs in a separate process, we also create a new fastify app each time  in the tests if I am not mistaken (not sure about if this contributes though). I can confirm I only see one warning on prod environments when launching a server.

2023-09-15 07:09 UTC, dnlup requested changes
All looks good here, can you just change the commit message to follow conventional commit convention? Something like `fix: remove fastify deprecation warning` should do it 😉

2023-09-15 09:01 UTC, tomasstrejcek commented
@dnlup ready :)

2023-09-15 10:03 UTC, dnlup approved these changes
Thanks!

2023-09-15 10:12 UTC, merged

2023-09-15 10:17 UTC, simonecorsi commented
:tada: This PR is included in version 7.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@immobiliarelabs/fastify-sentry/v/7.1.1)
- [GitHub release](https://github.com/immobiliare/fastify-sentry/releases/tag/v7.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: